services:
  - type: web
    name: todo-api
    env: ruby
    plan: free
    buildCommand: "bundle install && bundle exec rake db:migrate"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo-api-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true

databases:
  - name: todo-api-db